services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecoa-network

  redis:
    image: redis/redis-stack-server:7.4.0-v0
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ecoa-network

  minio:
    image: bitnami/minio:2024.9.13
    ports:
      - '${MINIO_PORT}:9000'
      - '${MINIO_UI_PORT}:9001'
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: 'sso-storage:private,sso-storage-public:public,mypages-storage:private,mypages-storage-public:public'
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - ecoa-network

volumes:
  postgres-data:
  redis-data:
  minio-data:

networks:
  ecoa-network:
    driver: bridge
